name: Deploy to EKS
on:
  workflow_run:
    workflows:
      - "Patient Service CI"
      - "Appointment Service CI"
      - "Notification Service CI"
      - "Aggregator Service CI"
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up job
      #   run: echo "Setting up deployment job..."

      - name: Run actions/checkout@v2
        run: echo "Checking out code..."

      - name: Configure AWS credentials
        run: echo "Configuring mock AWS credentials..."

      - name: Update kube config
        run: echo "Simulating kubeconfig update..."

      - name: Update deployment files with SHA
        run: echo "Updating deployment files..."

      - name: Deploy to EKS
        run: echo "Simulating EKS deployment..."

      - name: Verify deployments
        run: echo "Verifying deployments..."

      - name: Post Configure AWS credentials
        run: echo "Post AWS credentials cleanup..."

      - name: Post Run actions/checkout@v2
        run: echo "Post checkout cleanup..."

      # - name: Complete job
      #   run: echo "Deployment simulation completed"
