name: Patient Service CI

on:
  push:
    paths:
      - 'patient_record_service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Unit Test Step (this step would run actual tests in a real scenario)
      - name: Run Unit Tests
        run: |
          echo "Running Unit Tests... (This is just a placeholder)"
          # Normally, this would be: pytest tests/
      
      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and Push Docker Image (this step would perform real Docker build & push in a real scenario)
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Building and Pushing Docker Image... (This is just a placeholder)"
          # Normally, this would be:
          # docker build -t $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA ./patient_record_service
          # docker push $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA
          # docker tag $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA $ECR_REGISTRY/healthsync-patient-service:latest
          # docker push $ECR_REGISTRY/healthsync-patient-service:latest

      # Mark completion
      - name: Complete Workflow
        run: echo "Workflow has completed successfully without executing the actual tasks."
