name: Patient Service CI

on:
  push:
    paths:
      - 'patient_record_service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run Integration Tests
        id: int-test
        run: |
          echo "Running integration tests for the patient record service"
          # Replace the following command with your actual test runner command
          cd ./patient_record_service && ./run_tests.sh
          echo "Integration tests completed successfully"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Building image: $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA"
          docker build -t $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA ./patient_record_service
          echo "Pushing image: $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA"
          docker push $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA
          echo "Tagging image as latest: $ECR_REGISTRY/healthsync-patient-service:latest"
          docker tag $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA $ECR_REGISTRY/healthsync-patient-service:latest
          docker push $ECR_REGISTRY/healthsync-patient-service:latest
