name: Patient Service CI
on:
  push:
    paths:
      - 'patient_record_service/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v2
        run: echo "Checking out code..."

      - name: Run Unit Tests
        run: echo "Running patient service unit tests..."

      - name: Configure AWS Credentials
        run: echo "Configuring mock AWS credentials..."

      - name: Login to Amazon ECR
        run: echo "Simulating ECR login..."

      - name: Build and Push
        run: echo "Simulating build and push for patient service..."

      - name: Post Login to Amazon ECR
        run: echo "Post ECR login cleanup..."

      - name: Post Configure AWS Credentials
        run: echo "Post AWS credentials cleanup..."

      - name: Post Run actions/checkout@v2
        run: echo "Post checkout cleanup..."

      - name: Complete job
        run: echo "Patient service CI simulation completed"
