name: Patient Service CI
on:
  push:
    paths:
      - 'patient_record_service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA ./patient_record_service
          docker push $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA
          docker tag $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA $ECR_REGISTRY/healthsync-patient-service:latest
          docker push $ECR_REGISTRY/healthsync-patient-service:latest
        