name: Patient Service CI Test

on:
  push:
    paths:
      - 'patient_record_service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mock AWS Credentials
        run: |
          echo "Using mock AWS credentials"
          echo "AWS_ACCESS_KEY_ID=mock-key" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=mock-secret" >> $GITHUB_ENV
          echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV

      - name: Mock ECR Login
        id: login-ecr
        run: |
          echo "::set-output name=registry::mock-registry.dkr.ecr.ap-south-1.amazonaws.com"

      - name: Simulate Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Building image: $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA"
          echo "Would execute: docker build -t $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA ./patient_record_service"
          echo "Would push to: $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA"
          echo "Would tag as: $ECR_REGISTRY/healthsync-patient-service:latest"
          echo "Would push latest tag"

      - name: Verify Simulation
        run: |
          echo "Simulation completed successfully"
          echo "Image would be available at: $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA"
          echo "Latest tag would be updated"
